# Generated by Django 2.2.7 on 2020-03-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portola', '0004_follow_follower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ('-created',)},
        )
    ]
