# Generated by Django 2.2.7 on 2020-05-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portola', '0005_auto_20200323_2359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-issued_date']},
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='entity',
            name='type',
            field=models.CharField(choices=[['PARTNER', 'Downstream Partner'], ['CLIENT', 'Downstream Client'], ['MANUFACTURER', 'Manufacturer'], ['PVEL', 'PVEL']], db_index=True, default='PARTNER', max_length=100),
        ),
    ]
