# Generated by Django 2.2.7 on 2020-06-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portola', '0008_auto_20200603_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[['MIAM', 'Module IAM Report'], ['INTAKE', 'Intake'], ['FWR', 'Factory Witness Report'], ['IFT', 'Inverter Field Testing - Other'], ['IPQPF', 'Inverter PQP Final'], ['IPQPILT', 'Inverter PQP Interim'], ['MFT', 'Module Field Testing - Other'], ['MINTAKE', 'Module Intake'], ['MLID', 'Module LID'], ['MDML', 'Module Mechanical Load (Static, Dynamic, Other)'], ['MNOCT', 'Module NOCT'], ['MPANF', 'Module PAN File'], ['MPANR', 'Module PAN Report'], ['MPID', 'Module PID Testing'], ['MPQPF', 'Module PQP Final'], ['MPQPFE', 'Module PQP Field Exposure'], ['MPQPI1', 'Module PQP Interim 1'], ['MPQPI2', 'Module PQP Interim 2'], ['MPQPI3', 'Module PQP Interim 3'], ['MISC', 'Miscellaneous'], ['MCEY', 'Module Comparative Energy Yield'], ['RIE', 'Racking Installation Efficiency'], ['BDSI', 'Backsheet Durability Sequence Interim'], ['BDS', 'Backsheet Durability Sequence Final'], ['ER', 'Engineering Report'], ['RTR', 'Racking or Tracker Report'], ['ESPQPI', 'Energy Storage PQP Interim'], ['ESPQPF', 'Energy Storage PQP Final'], ['MPQPFEI', 'Module PQP Interim Field Exposure'], ['MLETID', 'Module LeTID ']], db_index=True, default='REPORT', max_length=32),
        ),
    ]
