# Generated by Django 2.2.7 on 2020-06-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portola', '0009_auto_20200606_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[['DS', 'Data Services (Includes SSD participants)'], ['ENGSC', 'Eng Services/ Strategic Consulting'], ['FAT', 'Factory Acceptance Testing'], ['GOVGRNT', 'Government Grants'], ['IFT', 'Inverter Field Testing (customer site)'], ['IMISC', 'Inverter Other (Includes RSD, AFCI)'], ['IPQP', 'Inverter PQP'], ['MFT', 'Module Field Testing (customer site)'], ['MHTMI', 'Module HTMI'], ['MMISC', 'Module Other'], ['MFPID', 'Module Flash, PAN, IAM, DML'], ['MPQP', 'Module PQP'], ['PVUSA', 'PV-USA (Includes Tracker/CEY)'], ['REFC', 'Ref Cells'], ['SMISC', 'Storage Other'], ['SPQP', 'Storage PQP'], ['SBURN', 'Storage - Burn'], ['PEO', 'Power Electronics Other']], db_index=True, default='MPQP', max_length=100),
        ),
    ]
