# Generated by Django 2.2.7 on 2020-06-23 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portola', '0011_auto_20200616_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contract_signature',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='last_document_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portola.Entity'),
        ),
        migrations.AddField(
            model_name='document',
            name='bom',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
