# Generated by Django 2.2.7 on 2020-09-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portola', '0012_auto_20200623_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='product_type',
            field=models.CharField(choices=[['modules', 'Modules'], ['racking', 'Racking'], ['inverter', 'Inverter'], ['optimizer', 'Optimizer'], ['Power Electronics', 'Power Electronics'], ['ess', 'Energy Storage System']], db_index=True, default='MODULES', max_length=32),
        ),
    ]
